// <auto-generated />
using System;
using Forum.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Forum.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Forum.Entity.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e653dd5a-265b-495f-84d9-5955bb0a7a7d"),
                            CreatedDate = new DateTime(2025, 5, 18, 19, 13, 4, 72, DateTimeKind.Local).AddTicks(600),
                            Name = "Bilgisayar"
                        },
                        new
                        {
                            Id = new Guid("549af326-eab0-4e1b-9422-b399cc24a53d"),
                            CreatedDate = new DateTime(2025, 5, 18, 19, 13, 4, 72, DateTimeKind.Local).AddTicks(610),
                            Name = "Oyun"
                        });
                });

            modelBuilder.Entity("Forum.Entity.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e020343d-b540-46da-8e65-22c7c01bdf46"),
                            Content = "Ryzen performans acisindan daha iyi diye biliyorum",
                            CreatedDate = new DateTime(2025, 5, 18, 16, 13, 4, 72, DateTimeKind.Utc).AddTicks(3292),
                            PostId = new Guid("188e009b-6406-4142-9928-037701d1c287")
                        },
                        new
                        {
                            Id = new Guid("787de76b-a155-4759-9cbd-a630bb7a19dd"),
                            Content = "Ryzen benchmark testlerinde daha ustun gozukuyor",
                            CreatedDate = new DateTime(2025, 5, 18, 16, 13, 4, 72, DateTimeKind.Utc).AddTicks(3296),
                            PostId = new Guid("188e009b-6406-4142-9928-037701d1c287")
                        },
                        new
                        {
                            Id = new Guid("63e0c121-6ea1-42b1-a6d2-a13a0b698d80"),
                            Content = "Hikaye bakimindan GOW acik dunya bakimindan RDR2 daha iyi bence",
                            CreatedDate = new DateTime(2025, 5, 18, 16, 13, 4, 72, DateTimeKind.Utc).AddTicks(3298),
                            PostId = new Guid("810710c9-d2a7-418e-a4a5-48effc80c4df")
                        });
                });

            modelBuilder.Entity("Forum.Entity.Entities.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("188e009b-6406-4142-9928-037701d1c287"),
                            CategoryId = new Guid("e653dd5a-265b-495f-84d9-5955bb0a7a7d"),
                            Content = "Etiam id velit feugiat, scelerisque velit a, scelerisque nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Integer dignissim risus non nibh scelerisque, sit amet tincidunt sapien rutrum.Integer a ipsum vitae urna varius egestas. Integer laoreet, sapien eget vehicula vehicula, odio lorem scelerisque magna, nec gravida libero nulla eget risus. Nulla facilisi. Donec at magna ut nulla pharetra cursus. Curabitur auctor, tellus in congue vestibulum, lacus lacus convallis justo, at fermentum libero felis nec ligula.Phasellus ac eros at urna condimentum lacinia. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed bibendum, sapien a venenatis fermentum, mauris augue cursus turpis, vitae elementum massa orci sit amet massa. In hac habitasse platea dictumst.",
                            CreatedDate = new DateTime(2025, 5, 18, 19, 13, 4, 72, DateTimeKind.Local).AddTicks(5844),
                            Title = "Amd Ryzen 4 vs Intel i5 11000h karsilastirmasi"
                        },
                        new
                        {
                            Id = new Guid("810710c9-d2a7-418e-a4a5-48effc80c4df"),
                            CategoryId = new Guid("549af326-eab0-4e1b-9422-b399cc24a53d"),
                            Content = "Etiam id velit feugiat, scelerisque velit a, scelerisque nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Integer dignissim risus non nibh scelerisque, sit amet tincidunt sapien rutrum.Integer a ipsum vitae urna varius egestas. Integer laoreet, sapien eget vehicula vehicula, odio lorem scelerisque magna, nec gravida libero nulla eget risus. Nulla facilisi. Donec at magna ut nulla pharetra cursus. Curabitur auctor, tellus in congue vestibulum, lacus lacus convallis justo, at fermentum libero felis nec ligula.Phasellus ac eros at urna condimentum lacinia. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed bibendum, sapien a venenatis fermentum, mauris augue cursus turpis, vitae elementum massa orci sit amet massa. In hac habitasse platea dictumst.",
                            CreatedDate = new DateTime(2025, 5, 18, 19, 13, 4, 72, DateTimeKind.Local).AddTicks(5854),
                            Title = "RDR2 vs GOW"
                        });
                });

            modelBuilder.Entity("Forum.Entity.Entities.Comment", b =>
                {
                    b.HasOne("Forum.Entity.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Forum.Entity.Entities.Post", b =>
                {
                    b.HasOne("Forum.Entity.Entities.Category", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Forum.Entity.Entities.Category", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("Forum.Entity.Entities.Post", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
